package FEApp;


/**
* FEApp/feInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/alekh/eclipse-workspace/DLMS_Project/src/FrontEnd/feInterface.idl
* Thursday, March 21, 2019 1:37:57 o'clock PM EDT
*/

public interface feInterface extends feInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface feInterface
