package FEApp;


/**
* FEApp/feInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/alekh/eclipse-workspace/DLMS_Project/src/FrontEnd/feInterface.idl
* Thursday, March 21, 2019 1:37:57 o'clock PM EDT
*/

public interface feInterfaceOperations 
{
  String addItem (String managerID, String itemID, String itemName, int quantity);
  String removeItem (String managerID, String itemID, int quantity);
  String listItemAvailability (String managerID);

  //Operations performed by user
  String borrowItem (String userID, String itemID, boolean isWaitlisted);
  String findItem (String userID, String itemName);
  String returnItem (String userID, String itemID);
  String exchangeItem (String userID, String oldItemID, String newItemID);
} // interface feInterfaceOperations
