package FEApp;

/**
* FEApp/feInterfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/alekh/eclipse-workspace/DLMS_Project/src/FrontEnd/feInterface.idl
* Thursday, March 21, 2019 1:37:57 o'clock PM EDT
*/

public final class feInterfaceHolder implements org.omg.CORBA.portable.Streamable
{
  public FEApp.feInterface value = null;

  public feInterfaceHolder ()
  {
  }

  public feInterfaceHolder (FEApp.feInterface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FEApp.feInterfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FEApp.feInterfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FEApp.feInterfaceHelper.type ();
  }

}
